// <auto-generated />
using System;
using AprendeTEA_19032025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AprendeTEA_19032025.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250422231739_PlanTrabajoUpdate")]
    partial class PlanTrabajoUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AprendeTEA_19032025.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("AprendeTEA_19032025.Models.PlanTrabajo", b =>
                {
                    b.Property<int>("IdPlanTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanTrabajo"));

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePlan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlanTrabajo");

                    b.ToTable("PlanTrabajo");
                });

            modelBuilder.Entity("AprendeTEA_19032025.Models.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPlanTrabajo")
                        .HasColumnType("int");

                    b.Property<string>("NombreUnidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanTrabajoIdPlanTrabajo")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnidad");

                    b.HasIndex("PlanTrabajoIdPlanTrabajo");

                    b.ToTable("Unidad");
                });

            modelBuilder.Entity("AprendeTEA_19032025.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AprendeTEA_19032025.Models.Unidad", b =>
                {
                    b.HasOne("AprendeTEA_19032025.Models.PlanTrabajo", null)
                        .WithMany("Unidades")
                        .HasForeignKey("PlanTrabajoIdPlanTrabajo");
                });

            modelBuilder.Entity("AprendeTEA_19032025.Models.PlanTrabajo", b =>
                {
                    b.Navigation("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
